# Generated by Django 3.2.12 on 2022-03-20 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('userAgent', models.CharField(max_length=256, null=True)),
                ('path', models.CharField(max_length=256, null=True)),
                ('isAdminPanel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('pair', models.CharField(max_length=20)),
                ('pairPrice', models.FloatField()),
                ('orderType', models.CharField(default=None, max_length=15)),
                ('histAmount', models.JSONField(default=None)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField(default=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trade histories',
            },
        ),
        migrations.CreateModel(
            name='SpotOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('pair', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('pairPrice', models.FloatField(null=True)),
                ('mortgage', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Spot Orders',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptoName', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0, null=True)),
                ('equivalentAmount', models.FloatField(blank=True, default=0, null=True)),
                ('marketType', models.CharField(default='spot', max_length=10)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuturesOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('pair', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=100)),
                ('entryPrice', models.FloatField()),
                ('marketPrice', models.FloatField()),
                ('liqPrice', models.FloatField()),
                ('leverage', models.IntegerField()),
                ('orderType', models.CharField(max_length=15)),
                ('marginType', models.CharField(max_length=10)),
                ('complete', models.BooleanField(default=False)),
                ('pnl', models.FloatField(default=0)),
                ('triggerConditions', models.FloatField(blank=True, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Futures Orders',
            },
        ),
        migrations.CreateModel(
            name='FuturesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histAmount', models.JSONField(default=None)),
                ('terminateDate', models.DateTimeField(auto_now_add=True)),
                ('orderDetails', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.futuresorders')),
            ],
            options={
                'verbose_name_plural': 'Future histories',
            },
        ),
    ]
