# Generated by Django 4.0.6 on 2022-08-01 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('pair', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=100)),
                ('entryPrice', models.FloatField()),
                ('marketPrice', models.FloatField()),
                ('liqPrice', models.FloatField()),
                ('leverage', models.IntegerField()),
                ('orderType', models.CharField(max_length=15)),
                ('marginType', models.CharField(max_length=10)),
                ('complete', models.BooleanField(default=False)),
                ('pnl', models.FloatField(default=0)),
                ('triggerConditions', models.FloatField(blank=True, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Futures Orders',
            },
        ),
        migrations.CreateModel(
            name='FuturesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histAmount', models.JSONField(default=None)),
                ('terminateDate', models.DateTimeField(auto_now_add=True)),
                ('orderDetails', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='future.futuresorders')),
            ],
            options={
                'verbose_name_plural': 'Future histories',
            },
        ),
    ]
