# Generated by Django 4.0.6 on 2022-08-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitorders',
            name='amount_float',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='limitorders',
            name='amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='limitorders',
            name='pair',
            field=models.CharField(max_length=255),
        ),
    ]
