# Generated by Django 4.0.6 on 2022-08-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit_order', '0002_limitorders_amount_float_alter_limitorders_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitorders',
            name='equivalentAmount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
