# Generated by Django 3.2.3 on 2021-10-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cryptoName', models.CharField(default=None, max_length=10)),
                ('price', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.CharField(default='0', max_length=15)),
                ('equivalentAmount', models.CharField(default='0', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('cryptoName', models.CharField(default=None, max_length=10)),
                ('price', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.CharField(default='0', max_length=15)),
                ('equivalentAmount', models.CharField(default='0', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UsrRegistration',
            fields=[
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=35)),
                ('nationalId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('phoneNumber', models.IntegerField()),
                ('mobileNumber', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=35)),
                ('mainBalance', models.CharField(default='1000', max_length=10)),
            ],
        ),
    ]
