# Generated by Django 4.0.6 on 2022-08-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('userAgent', models.CharField(max_length=256, null=True)),
                ('path', models.CharField(max_length=256, null=True)),
                ('isAdminPanel', models.BooleanField(default=False)),
            ],
        ),
    ]
