# Generated by Django 4.0.6 on 2022-08-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_remove_futureshistory_orderdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradehistory',
            name='price',
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='amount',
            field=models.CharField(max_length=10),
        ),
    ]
