# Generated by Django 4.0.6 on 2022-09-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_portfolio_cryptoname_alter_tradehistory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='marketType',
            field=models.CharField(choices=[('spot', 'spot'), ('futures', 'futures')], default='spot', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='histAmount',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='orderType',
            field=models.CharField(choices=[('market', 'market'), ('limit', 'limit')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4),
        ),
    ]
