# Generated by Django 4.0.6 on 2022-08-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotOrders',
        ),
    ]
